[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.8.0-alpha"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/MHAlikhani/rahn"
authors = ["Mohammad Hossein Alikhani", "The RAHN Project Contributors"]

[workspace.dependencies]
rahn-core = { path = "crates/rahn-core" }
rahn-state = { path = "crates/rahn-state" }
rahn-store = { path = "crates/rahn-store" }
rahn-verify = { path = "crates/rahn-verify" }
rahn-sim = { path = "crates/rahn-sim" }
rahn-exec = { path = "crates/rahn-exec" }
rahn-dist = { path = "crates/rahn-dist" }
rahn-sdk = { path = "crates/rahn-sdk" }
sha2 = { version = "0.10", default-features = false }
