[package]
name = "rahn-core"
description = "Core object model for RAHN: nodes, links, networks, states."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
